presubmit:
- name: sample-echo-test
  context: sample-echo-test
  always_run: true
  spec:
    containers:
    - image: c6h3un/toolbox:0.1.0
      command: ["curl"]
      args:
      - -s
      - http://echo.dev.svc/
