triggers:
- repos:
  - chulifelogger
  trusted_org: chulifelogger
  only_org_members: true

plugins:
  chulifelogger:
  - size
  - cat
  - trigger
  - lgtm
  - approve
  - assign

  chulifelogger/test-infra:
  - config-updater

config_updater:
  maps:
    config/label_sync.yaml:
      name: label-config
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

approve:
- repos:
  - chulifelogger
  implicit_self_approve: true
  lgtm_acts_as_approve: true
